// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADXsuCq3K2DzLeSY3Nd1MRT0xQETJ3e_g',
    appId: '1:20015357996:web:543a04432f39d84ea97189',
    messagingSenderId: '20015357996',
    projectId: 'expenso-108ad',
    authDomain: 'expenso-108ad.firebaseapp.com',
    storageBucket: 'expenso-108ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRmWrCgiZg-VmIHDNvFlxN9K7LDw4UqU',
    appId: '1:20015357996:android:bef5323baad5f533a97189',
    messagingSenderId: '20015357996',
    projectId: 'expenso-108ad',
    storageBucket: 'expenso-108ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnVm6oEchb7Lh0XTYUGCunw4BX4IEcOQ',
    appId: '1:20015357996:ios:eb17053a4d22ede5a97189',
    messagingSenderId: '20015357996',
    projectId: 'expenso-108ad',
    storageBucket: 'expenso-108ad.appspot.com',
    iosClientId: '20015357996-esc1u9bqidjhms116dimn4gnkh0lgego.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenso',
  );
}
